using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SimpleLed;

namespace Driver.Razer
{
    public static class RazerHIDS
    {
        public static List<USBDevice> RazerUsbDevices = new List<USBDevice>
        {
            new USBDevice{VID = 0x1532, HID = 0x010D, DevicePrettyName = "BlackWidow Ultimate 2012", DeviceName = "BlackWidow Ultimate 2012", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x010E, DevicePrettyName = "BlackWidow Classic (Alternate)", DeviceName = "BlackWidow Classic (Alternate)", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x010F, DevicePrettyName = "Anansi", DeviceName = "Anansi", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x011A, DevicePrettyName = "BlackWidow Ultimate 2013", DeviceName = "BlackWidow Ultimate 2013", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x011B, DevicePrettyName = "BlackWidow Stealth", DeviceName = "BlackWidow Stealth", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x2200, DevicePrettyName = "DeathStalker Expert", DeviceName = "DeathStalker Expert", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x2300, DevicePrettyName = "BlackWidow Chroma", DeviceName = "BlackWidow Chroma", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x2400, DevicePrettyName = "DeathStalker Chroma", DeviceName = "DeathStalker Chroma", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x2500, DevicePrettyName = "Blade Stealth", DeviceName = "Blade Stealth", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x2900, DevicePrettyName = "BlackWidow Tournament Edition Chroma", DeviceName = "BlackWidow Tournament Edition Chroma", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x020F, DevicePrettyName = "Blade QHD", DeviceName = "Blade QHD", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x3000, DevicePrettyName = "Blade Pro (Late 2016)", DeviceName = "Blade Pro (Late 2016)", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x3100, DevicePrettyName = "BlackWidow Chroma (Overwatch)", DeviceName = "BlackWidow Chroma (Overwatch)", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x3400, DevicePrettyName = "BlackWidow Ultimate 2016", DeviceName = "BlackWidow Ultimate 2016", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x3600, DevicePrettyName = "BlackWidow X Chroma", DeviceName = "BlackWidow X Chroma", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x3700, DevicePrettyName = "BlackWidow X Ultimate", DeviceName = "BlackWidow X Ultimate", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x021A, DevicePrettyName = "BlackWidow X Tournament Edition Chroma", DeviceName = "BlackWidow X Tournament Edition Chroma", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x021E, DevicePrettyName = "Ornata Chroma", DeviceName = "Ornata Chroma", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x021F, DevicePrettyName = "Ornata", DeviceName = "Ornata", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x4000, DevicePrettyName = "Blade Stealth (Late 2016)", DeviceName = "Blade Stealth (Late 2016)", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x4100, DevicePrettyName = "BlackWidow Chroma V2", DeviceName = "BlackWidow Chroma V2", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x4400, DevicePrettyName = "Blade (Late 2016)", DeviceName = "Blade (Late 2016)", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x4500, DevicePrettyName = "Blade Pro (2017)", DeviceName = "Blade Pro (2017)", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x4600, DevicePrettyName = "Huntsman Elite", DeviceName = "Huntsman Elite", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x4700, DevicePrettyName = "Huntsman", DeviceName = "Huntsman", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x4800, DevicePrettyName = "BlackWidow Elite", DeviceName = "BlackWidow Elite", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x022A, DevicePrettyName = "Cynosa Chroma", DeviceName = "Cynosa Chroma", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x022D, DevicePrettyName = "Blade Stealth (Mid 2017)", DeviceName = "Blade Stealth (Mid 2017)", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x022F, DevicePrettyName = "Blade Pro FullHD (2017)", DeviceName = "Blade Pro FullHD (2017)", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x5200, DevicePrettyName = "Blade Stealth (Late 2017)", DeviceName = "Blade Stealth (Late 2017)", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x5300, DevicePrettyName = "Blade 15 (2018)", DeviceName = "Blade 15 (2018)", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x5400, DevicePrettyName = "Blade Pro 17 (2019)", DeviceName = "Blade Pro 17 (2019)", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x5500, DevicePrettyName = "BlackWidow Lite (2018)", DeviceName = "BlackWidow Lite (2018)", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x5700, DevicePrettyName = "BlackWidow Essential", DeviceName = "BlackWidow Essential", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1535, HID = 0x5900, DevicePrettyName = "Blade Stealth (2019)", DeviceName = "Blade Stealth (2019)", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x023A, DevicePrettyName = "Blade 15 (2019) Advanced", DeviceName = "Blade 15 (2019) Advanced", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x023B, DevicePrettyName = "Blade 15 (2018) Base Model", DeviceName = "Blade 15 (2018) Base Model", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x023F, DevicePrettyName = "Cynosa Lite", DeviceName = "Cynosa Lite", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1536, HID = 0x0000, DevicePrettyName = "Blade 15 (2018) Mercury", DeviceName = "Blade 15 (2018) Mercury", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1536, HID = 0x0100, DevicePrettyName = "BlackWidow (2019)", DeviceName = "BlackWidow (2019)", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1536, HID = 0x0300, DevicePrettyName = "Huntsman Tournament Edition", DeviceName = "Huntsman Tournament Edition", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1536, HID = 0x0500, DevicePrettyName = "Blade 15 (Mid 2019) Mercury", DeviceName = "Blade 15 (Mid 2019) Mercury", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1536, HID = 0x0600, DevicePrettyName = "Blade 15 (Mid 2019) Base", DeviceName = "Blade 15 (Mid 2019) Base", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x024A, DevicePrettyName = "Blade Stealth (Late 2019)", DeviceName = "Blade Stealth (Late 2019)", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x024C, DevicePrettyName = "Blade Pro (Late 2019)", DeviceName = "Blade Pro (Late 2019)", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x024D, DevicePrettyName = "Blade 15 Studio Edition (2019)", DeviceName = "Blade 15 Studio Edition (2019)", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1536, HID = 0x1200, DevicePrettyName = "Blade Stealth (Early 2020)", DeviceName = "Blade Stealth (Early 2020)", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1536, HID = 0x1300, DevicePrettyName = "Blade 15 Advanced (2020)", DeviceName = "Blade 15 Advanced (2020)", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1536, HID = 0x1500, DevicePrettyName = "Blade 15 (Early 2020) Base", DeviceName = "Blade 15 (Early 2020) Base", DeviceType = DeviceTypes.Keyboard, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x1300, DevicePrettyName = "Orochi 2011", DeviceName = "Orochi 2011", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x1600, DevicePrettyName = "DeathAdder 3.5G", DeviceName = "DeathAdder 3.5G", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x2000, DevicePrettyName = "Abyssus 1800", DeviceName = "Abyssus 1800", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x2400, DevicePrettyName = "Mamba 2012 (Wired)", DeviceName = "Mamba 2012 (Wired)", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x2500, DevicePrettyName = "Mamba 2012 (Wireless)", DeviceName = "Mamba 2012 (Wireless)", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x002E, DevicePrettyName = "Naga 2012", DeviceName = "Naga 2012", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x002F, DevicePrettyName = "Imperator 2012", DeviceName = "Imperator 2012", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x3200, DevicePrettyName = "Ouroboros 2012", DeviceName = "Ouroboros 2012", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x3400, DevicePrettyName = "Taipan", DeviceName = "Taipan", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x3600, DevicePrettyName = "Naga Hex (Red)", DeviceName = "Naga Hex (Red)", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x3700, DevicePrettyName = "DeathAdder 2013", DeviceName = "DeathAdder 2013", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x3800, DevicePrettyName = "DeathAdder 1800", DeviceName = "DeathAdder 1800", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x3900, DevicePrettyName = "Orochi 2013", DeviceName = "Orochi 2013", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x4000, DevicePrettyName = "Naga 2014", DeviceName = "Naga 2014", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x4100, DevicePrettyName = "Naga Hex", DeviceName = "Naga Hex", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x4200, DevicePrettyName = "Abyssus 2014", DeviceName = "Abyssus 2014", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x4300, DevicePrettyName = "DeathAdder Chroma", DeviceName = "DeathAdder Chroma", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x4400, DevicePrettyName = "Mamba (Wired)", DeviceName = "Mamba (Wired)", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x4500, DevicePrettyName = "Mamba (Wireless)", DeviceName = "Mamba (Wireless)", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x4600, DevicePrettyName = "Mamba Tournament Edition", DeviceName = "Mamba Tournament Edition", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x4800, DevicePrettyName = "Orochi (Wired)", DeviceName = "Orochi (Wired)", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x004C, DevicePrettyName = "Diamondback Chroma", DeviceName = "Diamondback Chroma", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x004F, DevicePrettyName = "DeathAdder 2000", DeviceName = "DeathAdder 2000", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x5000, DevicePrettyName = "Naga Hex V2", DeviceName = "Naga Hex V2", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x5300, DevicePrettyName = "Naga Chroma", DeviceName = "Naga Chroma", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x5400, DevicePrettyName = "DeathAdder 3500", DeviceName = "DeathAdder 3500", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x5900, DevicePrettyName = "Lancehead (Wired)", DeviceName = "Lancehead (Wired)", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x005A, DevicePrettyName = "Lancehead (Wireless)", DeviceName = "Lancehead (Wireless)", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x005B, DevicePrettyName = "Abyssus V2", DeviceName = "Abyssus V2", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x005C, DevicePrettyName = "DeathAdder Elite", DeviceName = "DeathAdder Elite", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x005E, DevicePrettyName = "Abyssus 2000", DeviceName = "Abyssus 2000", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1533, HID = 0x0000, DevicePrettyName = "Lancehead Tournament Edition", DeviceName = "Lancehead Tournament Edition", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1533, HID = 0x0200, DevicePrettyName = "Atheris (Receiver)", DeviceName = "Atheris (Receiver)", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1533, HID = 0x0400, DevicePrettyName = "Basilisk", DeviceName = "Basilisk", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1533, HID = 0x0700, DevicePrettyName = "Naga Trinity", DeviceName = "Naga Trinity", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x006A, DevicePrettyName = "Abyssus Elite (D.Va Edition)", DeviceName = "Abyssus Elite (D.Va Edition)", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x006B, DevicePrettyName = "Abyssus Essential", DeviceName = "Abyssus Essential", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x006C, DevicePrettyName = "Mamba Elite (Wired)", DeviceName = "Mamba Elite (Wired)", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x006E, DevicePrettyName = "DeathAdder Essential", DeviceName = "DeathAdder Essential", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x006F, DevicePrettyName = "Lancehead Wireless (Receiver)", DeviceName = "Lancehead Wireless (Receiver)", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1533, HID = 0x1000, DevicePrettyName = "Lancehead Wireless (Wired)", DeviceName = "Lancehead Wireless (Wired)", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1533, HID = 0x1100, DevicePrettyName = "DeathAdder Essential (White Edition)", DeviceName = "DeathAdder Essential (White Edition)", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1533, HID = 0x1200, DevicePrettyName = "Mamba Wireless (Receiver)", DeviceName = "Mamba Wireless (Receiver)", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1533, HID = 0x1300, DevicePrettyName = "Mamba Wireless (Wired)", DeviceName = "Mamba Wireless (Wired)", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1533, HID = 0x1800, DevicePrettyName = "Viper", DeviceName = "Viper", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x007A, DevicePrettyName = "Viper Ultimate (Wired)", DeviceName = "Viper Ultimate (Wired)", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x007B, DevicePrettyName = "Viper Ultimate (Wireless)", DeviceName = "Viper Ultimate (Wireless)", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1533, HID = 0x2300, DevicePrettyName = "Basilisk X HyperSpeed", DeviceName = "Basilisk X HyperSpeed", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1533, HID = 0x2400, DevicePrettyName = "DeathAdder V2", DeviceName = "DeathAdder V2", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x008A, DevicePrettyName = "Viper Mini", DeviceName = "Viper Mini", DeviceType = DeviceTypes.Mouse, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1533, HID = 0x0800, DevicePrettyName = "Firefly Hyperflux", DeviceName = "Firefly Hyperflux", DeviceType = DeviceTypes.MousePad, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x0C00, DevicePrettyName = "Firefly", DeviceName = "Firefly", DeviceType = DeviceTypes.MousePad, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x0C01, DevicePrettyName = "Goliathus", DeviceName = "Goliathus", DeviceType = DeviceTypes.MousePad, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x0C02, DevicePrettyName = "Goliathus Extended", DeviceName = "Goliathus Extended", DeviceType = DeviceTypes.MousePad, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1540, HID = 0x2100, DevicePrettyName = "Kraken 7.1", DeviceName = "Kraken 7.1", DeviceType = DeviceTypes.Headset, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1540, HID = 0x2400, DevicePrettyName = "Kraken 7.1 Chroma", DeviceName = "Kraken 7.1 Chroma", DeviceType = DeviceTypes.Headset, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1540, HID = 0x2600, DevicePrettyName = "Kraken 7.1", DeviceName = "Kraken 7.1", DeviceType = DeviceTypes.Headset, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1540, HID = 0x3000, DevicePrettyName = "Kraken 7.1 V2", DeviceName = "Kraken 7.1 V2", DeviceType = DeviceTypes.Headset, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1540, HID = 0x4700, DevicePrettyName = "Kraken Ultimate", DeviceName = "Kraken Ultimate", DeviceType = DeviceTypes.Headset, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x0207, DevicePrettyName = "Orbweaver", DeviceName = "Orbweaver", DeviceType = DeviceTypes.Keypad, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x0208, DevicePrettyName = "Tartarus", DeviceName = "Tartarus", DeviceType = DeviceTypes.Keypad, ManufacturerName = "Razer"},
new USBDevice{VID = 0x1532, HID = 0x022B, DevicePrettyName = "Tartarus V2", DeviceName = "Tartarus V2", DeviceType = DeviceTypes.Keypad, ManufacturerName = "Razer"},

        };
    }
}
